# Generated by Django 5.2.5 on 2025-09-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='edad',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
