# Generated by Django 5.2.5 on 2025-09-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0002_estudiante_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='edad',
            field=models.CharField(max_length=100),
        ),
    ]
