# Generated by Django 5.2.5 on 2025-09-12 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0003_alter_estudiante_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=100)),
                ('autorizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradores.administrador')),
                ('escritor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradores.estudiante')),
            ],
        ),
    ]
