# Generated by Django 5.2.5 on 2025-09-12 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0004_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='autorizado',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='escritor',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administradores.administrador'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administradores.estudiante'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
