# Generated by Django 5.2.5 on 2025-09-12 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0005_remove_publicacion_autorizado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='administrador',
            new_name='autorizado',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='estudiante',
            new_name='escritor',
        ),
    ]
